# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# cdo source code available at https://code.zmaw.de/projects/cdo/files

language: r
sudo: required
dist: trusty
cache: packages

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libhdf5-dev
      - libnetcdf-dev
      - cdo

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
  