# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# cdo source code available at https://code.zmaw.de/projects/cdo/files
# http://www.studytrails.com/blog/install-climate-data-operator-cdo-with-netcdf-grib2-and-hdf5-support/

language: r
sudo: required
cache: packages
      
before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap
  - cd
  - wget http://download.osgeo.org/gdal/2.0.1/gdal-2.0.1.tar.gz
  - tar zxf gdal-2.0.1.tar.gz
  - cd gdal-2.0.1
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.2.tar.gz
  - tar zxvf proj-4.9.2.tar.gz
  - cd proj-4.9.2
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd
  - wget https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.18.tar.gz
  - tar -xvf hdf5-1.8.18.tar.gz
  - cd hdf5-1.8.18
  - ./configure --prefix=/usr
  - make
  - make check
  - sudo make install
  - cd
  - wget https://github.com/Unidata/netcdf-c/archive/v4.4.1.tar.gz
  - tar zxvf v4.4.1.tar.gz
  - cd netcdf-c-4.4.1
  - ./configure --prefix=/usr
  - make 
  - make check
  - sudo make install
  - cd
  - wget https://code.zmaw.de/attachments/download/12760/cdo-1.7.2.tar.gz
  - tar zxvf cdo-1.7.2.tar.gz
  - cd cdo-1.7.2
  - ./configure --enable-netcdf4 --with-netcdf=/usr --prefix=/usr
  - make check
  - sudo make install
  - cd /home/travis/build/anywhereProject/caliver

r_github_packages:
  - jimhester/covr
  - anywhereProject/caliver

after_success:
  - Rscript -e 'covr::codecov()'
  