# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# cdo source code available at https://code.zmaw.de/projects/cdo/wiki/Libs4cdo
# (to configure) --prefix=/usr/local is the default option

language: r
sudo: required
dist: xenial

addons:
  apt:
  packages:
  - libgdal-dev
      
before_install:
  - wget https://code.zmaw.de/attachments/download/10301/libs4cdo-0.0.11.tar.gz
  - tar zxvf libs4cdo-0.0.11.tar.gz
  - cd libs4cdo-0.0.11
  - make libs4cdo
  - cd
  - wget https://code.zmaw.de/attachments/download/12760/cdo-1.7.2.tar.gz
  - tar zxvf cdo-1.7.2.tar.gz
  - cd cdo-1.7.2
  - ./configure --with-szlib=/home/travis/build/anywhereProject/caliver/libs4cdo-0.0.11/build --with-hdf5=/home/travis/build/anywhereProject/caliver/libs4cdo-0.0.11/build --with-netcdf=/home/travis/build/anywhereProject/caliver/libs4cdo-0.0.11/build --with-proj=/home/travis/build/anywhereProject/caliver/libs4cdo-0.0.11/build 
  - make
  - sudo make install
  - cd /home/travis/build/anywhereProject/caliver

r_github_packages:
  - jimhester/covr
  - anywhereProject/caliver

after_success:
  - Rscript -e 'covr::codecov()'
  