# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# cdo source code available at https://code.zmaw.de/projects/cdo/wiki/Libs4cdo
# (to configure) --prefix=/usr/local is the default option

language: r
sudo: required
dist: trusty
cache: packages

addons:
  apt:
    packages:
    - autopoint
    - cfortran
    - dh-autoreconf
    - dh-buildinfo
    - libcurl4-gnutls-dev
    - libemos-data
    - libemos0d
    - libgcrypt11-dev
    - libgnutls-dev
    - libgnutlsxx27
    - libgpg-error-dev
    - libgrib-api-1.10.4
    - libgrib-api-dev
    - libmagics++-data
    - libmagics++-dev
    - libmagplus3
    - libp11-kit-dev
    - libtasn1-6-dev
    - libterralib
    - ttf-dejavu-extra
    - libhdf5-dev
    - libnetcdf-dev
    - libproj-dev
    - libgdal-dev
    - netcdf-bin

before_install:
  - wget https://code.zmaw.de/attachments/download/11392/cdo-1.7.0.tar.gz
  - tar zxvf cdo-1.7.0.tar.gz
  - cd cdo-1.7.0
  - ./configure --with-hdf5=yes --with-netcdf=yes --with-proj=/usr/include
  - make check
  - sudo make install
  - cd ..
  - rm cdo-1.7.0.tar.gz
  - rm -rf cdo-1.7.0
  - cd /home/travis/build/ecmwf/caliver

r_github_packages:
  - jimhester/covr
  - ecmwf/caliver

after_success:
  - Rscript -e 'covr::codecov()'
