# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: trusty
r: bioc-devel
bioc_required: true
bioc_use_devel: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libhdf5-dev
      - libnetcdf-dev
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - libgdal-dev
      - ncl-ncarg
      - cdo

r_github_packages:
  - MangoTheCat/visualTest
  - jimhester/lintr
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
