# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
r: bioc-devel
bioc_required: true
bioc_use_devel: true

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap
  - cd
  - wget http://download.osgeo.org/gdal/2.0.1/gdal-2.0.1.tar.gz
  - tar zxf gdal-2.0.1.tar.gz
  - cd gdal-2.0.1
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.2.tar.gz
  - tar zxvf proj-4.9.2.tar.gz
  - cd proj-4.9.2
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd
  - wget https://www.earthsystemgrid.org/dataset/ncl.640.src/file/ncl_ncarg-6.4.0.tar.gz
  - tar zxvf ncl_ncarg-6.4.0.tar.gz
  - cd ncl_ncarg-6.4.0
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd /home/travis/build/ecmwf/caliver
  - Rscript -e 'update.packages(ask = FALSE)'

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libssl-dev
      - libhdf5-dev
      - libnetcdf-dev
      - netcdf-bin
      - cdo

r_github_packages:
  - MangoTheCat/visualTest
  - jimhester/lintr
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
