# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: trusty
r: bioc-devel
bioc_required: true 
bioc_use_devel: true

addons:
  apt:
    packages:
    - libproj-dev
    - libgdal-dev
    - libhdf5-dev
    - libnetcdf-dev
    - netcdf-bin
    - ncl-ncarg
    - cdo
  
r_packages:
  - covr

r_github_packages:
  - MangoTheCat/visualTest
  - hadley/httr

after_success:
  - Rscript -e 'covr::codecov()'
