# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# cdo source code available at https://code.zmaw.de/projects/cdo/files

language: r
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libhdf5-dev
      - libnetcdf-dev
      
before_install:
  - wget https://code.zmaw.de/attachments/download/11392/cdo-1.7.2.tar.gz
  - tar zxvf cdo-1.7.2.tar.gz
  - cd cdo-1.7.2
  - ./configure --enable-netcdf4 --with-netcdf=/usr --prefix=/usr
  - make check
  - sudo make install
  - cd /home/travis/build/anywhereProject/caliver

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
  