# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: trusty
r: bioc-devel
bioc_required: true
bioc_use_devel: true

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos-dev libgdal-dev netcdf-bin

addons:
  apt:
    packages:
    - libhdf5-dev
    - libnetcdf-dev
    - libgdal1h
    - libncarg0
    - ncl-ncarg
    - cdo

r_github_packages:
  - MangoTheCat/visualTest
  - jimhester/lintr
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
