# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# cdo source code available at https://code.zmaw.de/projects/cdo/wiki/Libs4cdo
# (to configure) --prefix=/usr/local is the default option

language: r
sudo: required
cache: packages
      
before_install:
  - wget http://download.osgeo.org/gdal/2.0.1/gdal-2.0.1.tar.gz
  - tar zxf gdal-2.0.1.tar.gz
  - cd gdal-2.0.1
  - ./configure
  - make
  - sudo make install
  - cd
  - wget https://code.zmaw.de/attachments/download/10301/libs4cdo-0.0.11.tar.gz
  - tar zxvf libs4cdo-0.0.11.tar.gz
  - cd libs4cdo-0.0.11
  - make config all install
  - sudo make install
  - cd
  - wget https://code.zmaw.de/attachments/download/12760/cdo-1.7.2.tar.gz
  - tar zxvf cdo-1.7.2.tar.gz
  - cd cdo-1.7.2
  - ./configure --with-szlib=/usr/local/libs4cdo-0.0.11/build --with-hdf5=/usr/local/libs4cdo-0.0.11/build --with-netcdf=/usr/local/libs4cdo-0.0.11/build --with-proj=/usr/local/libs4cdo-0.0.11/build
  - make
  - sudo make install
  - cd /home/travis/build/anywhereProject/caliver

r_github_packages:
  - jimhester/covr
  - anywhereProject/caliver

after_success:
  - Rscript -e 'covr::codecov()'
  