# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: trusty
r: bioc-devel
bioc_required: true 
bioc_use_devel: true

addons:
  apt:
    packages:
    - libcurl4-gnutls-dev
    - libgcrypt11-dev
    - libgnutls-dev
    - libgnutlsxx27
    - libgpg-error-dev
    - libp11-kit-dev
    - libtasn1-6-dev
    - libterralib
    - libproj-dev
    - libgdal-dev
    - libhdf5-dev
    - libnetcdf-dev
    - netcdf-bin
    - ncl-ncarg
    - cdo
  
r_packages:
  - rgdal
  - roxygen2
  - rprojroot
  - rmarkdown
  - png
  - htmltools
  - covr

r_github_packages:
  - MangoTheCat/visualTest

after_success:
  - Rscript -e 'covr::codecov()'
