# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: trusty

r: bioc-devel
bioc_required: true
bioc_use_devel: true

addons:
  apt:
    packages:
    - libnetcdf-dev
    - netcdf-bin
    - libhdf5-dev
    - libproj-dev
    - libgdal-dev
    - cdo

r_github_packages:
  - MangoTheCat/visualTest
  - jimhester/lintr
  - jimhester/covr
  - r-lib/pkgdown
  - ecmwf/caliver

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
