# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap
  - cd
  - wget http://download.osgeo.org/gdal/2.0.1/gdal-2.0.1.tar.gz
  - tar zxf gdal-2.0.1.tar.gz
  - cd gdal-2.0.1
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.2.tar.gz
  - tar zxvf proj-4.9.2.tar.gz
  - cd proj-4.9.2
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd
  - wget http://zlib.net/zlib-1.2.8.tar.gz
  - tar zxvf zlib-1.2.8.tar.gz
  - cd zlib-1.2.8
  - ZDIR=/usr/local
  - ./configure --prefix=${ZDIR}
  - make check
  - sudo make install
  - cd
  - wget https://support.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.17.tar
  - tar -xvf hdf5-1.8.17.tar
  - cd hdf5-1.8.17
  - H5DIR=/usr/local
  - ./configure --with-zlib=${ZDIR} --prefix=${H5DIR}
  - make check
  - sudo make install
  - cd
  - wget https://github.com/Unidata/netcdf-c/archive/v4.4.1.tar.gz
  - tar zxvf v4.4.1.tar.gz
  - cd v4.4.1
  - NCDIR=/usr/local
  - CPPFLAGS=-I${H5DIR}/include LDFLAGS=-L${H5DIR}/lib ./configure --prefix=${NCDIR}
  - make check
  - sudo make install
  - cd
  - wget http://www.ece.uvic.ca/~frodo/jasper/software/jasper-1.900.1.zip
  - unzip jasper-1.900.1.zip
  - cd jasper-1.900.1
  - JASPERDIR=/usr/local
  - ./configure –prefix=${JASPERDIR} CFLAGS=-fPIC
  - make check
  - sudo make install
  - cd
  - wget https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-1.14.4-Source.tar.gz?api=v2
  - tar zxvf grib_api-1.14.4-Source.tar.gz
  - cd grib_api-1.14.4-Source
  - GRIBDIR=/usr/local
  - ./configure –prefix=${GRIBDIR} CFLAGS=-fPIC  –with-netcdf=${NCDIR} –with-jasper=${JASPERDIR}
  - make check
  - sudo make install
  - cd
  - wget https://code.zmaw.de/attachments/download/11392/cdo-1.7.0.tar.gz
  - tar zxvf cdo-1.7.0.tar.gz
  - cd cdo-1.7.0
  - CDODIR=/usr/local
  - ./configure –prefix=${CDODIR} CFLAGS=-fPIC  –with-netcdf=${NCDIR} –with-jasper=${JASPERDIR} –with-hdf5=${H5DIR}  –with-grib_api=${GRIBDIR}
  - make check
  - sudo make install
  - cd /home/travis/build/anywhereProject/caliver

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
  