# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
dist: trusty
cache: packages

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libnetcdf-dev
      - libhdf5-dev
  
before_install:
  - wget https://code.zmaw.de/attachments/download/11392/cdo-1.7.0.tar.gz
  - tar zxvf cdo-1.7.0.tar.gz
  - cd cdo-1.7.0
  - ./configure --enable-netcdf4  --enable-zlib --with-netcdf=/usr/ --with-hdf5=/usr/
  - make check
  - sudo make install
  - cd /home/travis/build/anywhereProject/caliver

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
  